<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<SatelliteResourceLanguages>false</SatelliteResourceLanguages>
		<NoWarn>CS8600,CS8602,CS8632</NoWarn>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
	  <DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Contracts\NewFolder\**" />
	  <EmbeddedResource Remove="Contracts\NewFolder\**" />
	  <None Remove="Contracts\NewFolder\**" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="AutoMapper" Version="16.1.1" />
		<PackageReference Include="MailKit" Version="4.15.1" />
		<PackageReference Include="MediatR" Version="14.1.0" />
		<PackageReference Include="FluentValidation" Version="12.1.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Credenciamento.Infrastructure\Credenciamento.Infrastructure.csproj" />
	</ItemGroup>

</Project>
